### ISSUE TITLE
My Launcher Bug Fix

### ISSUE THREAD

**Issue by MetsukiMio** [CarmJos/CarmJos#6]
我启动器的确bug挺多的，但是在我电脑上几乎没问题，所以能请你帮我修复bug吗？

**Comment by huanmeng-qwq** [comment]
任何人都没有义务帮助你做任何事情。

**Comment by MetsukiMio** [comment]
if (everyone.contains(this)){
        System.out.println("What!I needn't fix bugs!");
}
else{
        System.out.println("So this is 2b2t?");
}

**Comment by MetsukiMio** [comment]
if (everyone.contains(this)){
System.out.println("什么！我不需要修bug！这本身就是一个bug！");
}
else if (evetyone.size() == this.world.getCount() - 1){
System.out.println("所以这是2b2t吗？");
}
else{
System.out.println("看来还是有人可以帮助我的");
}

**Comment by MetsukiMio** [comment]
if (this.currentUploader.isCommercialize){
System.out.println("这.....");
}
else{
System.out.println("这才是最正常的up主");
}

**Comment by CarmJos** [comment]
下文取自 [《开源指北》 _第 2 小节：个人为什么要参与开源贡献_](https://oschina.gitee.io/opensource-guide/guide/%E7%AC%AC%E4%B8%89%E9%83%A8%E5%88%86%EF%BC%9A%E5%B0%9D%E8%AF%95%E5%8F%82%E4%B8%8E%E5%BC%80%E6%BA%90/%E7%AC%AC%202%20%E5%B0%8F%E8%8A%82%EF%BC%9A%E4%B8%AA%E4%BA%BA%E4%B8%BA%E4%BB%80%E4%B9%88%E8%A6%81%E5%8F%82%E4%B8%8E%E5%BC%80%E6%BA%90%E8%B4%A1%E7%8C%AE/#%E5%89%8D%E8%A8%80) 。

> ## 参与开源可以解决个人诉求
> 
> 所谓“存在即合理”，任何事物的兴起，都是其出现的背后有强烈的诉求需要解决。开源领域的出现，就是在开源者为了满足自身促进交流的诉求而形成的。可以说，没有开源诉求，就没有开源的发展。开源者的诉求这里大致分为 4 种：
> 
> ### 个人兴趣
>
> 一些开源者最初只是单纯对开源领域感兴趣，有浓烈的好奇心，所以才加入开源社区。而后随着不断深入了解，最终成为一名优秀的开源者。
>
> ### 日常需求
>
>有些开源者是因为生活或工作中接触到了相关的开源技术，需要技术交流或解决问题，因此加入开源社区。
> 
> ### 技术提升
>
> 有一定技术基础的开源者，会产生提升个人技术的想法，想要为个人的职业规划发展打造个人品牌，所以加入开源社区进行技术深造。
>
> ### 生态推广
>
> 一些已经具备个人成果的开源者，会想要推广个人成果，一方面可以提升技术影响力，一方面可以打造自己的开源生态社区。
>
> 那么，个人为什么要开源者参与开源贡献？至此，已经有了第一份答案：因为开源者有开源诉求，为了解决个人诉求参与开源。也正是因此，开源领域才吸引越来越多的开源者参与其中，形成开源社区。

**Comment by CarmJos** [comment]
由于本人日常使用的官方启动器，没有使用第三方启动器的日常需求；且个人对MC启动器开发方面没有兴趣，更愿意从更大的开源项目中发展我个人技术实力。因此，本人可能暂时没有时间参与您项目的开发维护，对此我深感抱歉。

**Comment by MetsukiMio** [comment]
那似乎我不得不借鉴甚至把hmcl当作一个库了...

**Comment by CarmJos** [comment]
我把您的项目看了一遍，这里建议您整体进行重构，可以参考、依赖部分UI、CONF方面的开源类库，提高自己的开发效率。

**Comment by MetsukiMio** [comment]
o

**Comment by MetsukiMio** [comment]
这页面切换系统。。。这hmcl动画那么卡的原因应该也是因为hmcl变成了一座屎山..

**Comment by MetsukiMio** [comment]
除了页面切换系统其他还是挺正常的

**Comment by CarmJos** [comment]
这里给您推荐几个开源类库：

- [curtcox / JLHTTP](https://github.com/curtcox/JLHTTP)
Java Lightweight HTTP Server (Web Server)
推荐理由： 快捷进行HTTP操作
- [CarmJos / GithubReleases4J](https://github.com/CarmJos/GithubReleases4J)
GitHub Releases for Java , based on GitHub RESTful API .
推荐理由： 快速获取项目的更新并提示用户
- [CarmJos / EasyConfiguration](https://github.com/CarmJos/EasyConfiguration)
轻松(做)配置，简单便捷的通用配置文件加载、读取与更新工具，可自定义配置格式。
- [JFormDesigner / FlatLaf](https://github.com/JFormDesigner/FlatLaf)
FlatLaf - Swing Look and Feel (with Darcula/IntelliJ themes support)
推荐理由： 类IDEA的UI设计类库，快速构造美观且实用的UI。

**Comment by MetsukiMio** [comment]
其实我已经用上jfoenix控件库了，挺好用

**Comment by MetsukiMio** [comment]
自带动画的ui库多好

**Comment by huanmeng-qwq** [comment]
兄弟，你多大啊？@Jack253-png

**Comment by MetsukiMio** [comment]
https://github.com/sshahine/JFoenix

**Comment by MetsukiMio** [comment]
这个是jfoenix的ui库，hmcl也在用

**Comment by MetsukiMio** [comment]
其实..........

**Comment by MetsukiMio** [comment]
@huanmeng-qwq 其实我才11

**Comment by MetsukiMio** [comment]
这webkit虽然好用，但是还是挺坑的
java.lang.IllegalArgumentException: Texture must be non-null
	at com.sun.scenario.effect.impl.prism.PrTexture.<init>(PrTexture.java:38)
	at com.sun.scenario.effect.impl.prism.PrDrawable.<init>(PrDrawable.java:44)
	at com.sun.scenario.effect.impl.prism.ps.PPSDrawable.<init>(PPSDrawable.java:39)
	at com.sun.scenario.effect.impl.prism.ps.PPSDrawable.create(PPSDrawable.java:60)
	at com.sun.scenario.effect.impl.prism.ps.PPSRenderer.createCompatibleImage(PPSRenderer.java:163)
	at com.sun.scenario.effect.impl.prism.ps.PPSRenderer.createCompatibleImage(PPSRenderer.java:67)
	at com.sun.scenario.effect.impl.ImagePool.checkOut(ImagePool.java:183)
	at com.sun.scenario.effect.impl.Renderer.getCompatibleImage(Renderer.java:116)
	at com.sun.scenario.effect.impl.prism.ps.PPSRenderer.getCompatibleImage(PPSRenderer.java:168)
	at com.sun.scenario.effect.impl.prism.ps.PPSRenderer.getCompatibleImage(PPSRenderer.java:67)
	at com.sun.scenario.effect.Effect.getCompatibleImage(Effect.java:479)
	at com.sun.javafx.webkit.prism.WCGraphicsPrismContext$Layer.<init>(WCGraphicsPrismContext.java:1369)
	at com.sun.javafx.webkit.prism.WCGraphicsPrismContext$ClipLayer.<init>(WCGraphicsPrismContext.java:1440)
	at com.sun.javafx.webkit.prism.WCGraphicsPrismContext$ClipLayer.<init>(WCGraphicsPrismContext.java:1433)
	at com.sun.javafx.webkit.prism.WCGraphicsPrismContext.setClip(WCGraphicsPrismContext.java:328)
	at com.sun.webkit.graphics.GraphicsDecoder.decode(GraphicsDecoder.java:225)
	at com.sun.webkit.graphics.WCRenderQueue.decode(WCRenderQueue.java:92)
	at com.sun.webkit.WebPage.paint2GC(WebPage.java:736)
	at com.sun.webkit.WebPage.paint(WebPage.java:703)
	at com.sun.javafx.sg.prism.web.NGWebView.renderContent(NGWebView.java:95)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at com.sun.javafx.tk.quantum.ViewPainter.doPaint(ViewPainter.java:479)
	at com.sun.javafx.tk.quantum.ViewPainter.paintImpl(ViewPainter.java:328)
	at com.sun.javafx.tk.quantum.PresentingPainter.run(PresentingPainter.java:91)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by CarmJos** [comment]
这个提示是 “材质不能为空” 呀...

**Comment by MetsukiMio** [comment]
是decoder的问题

**Comment by MetsukiMio** [comment]
这webkit不是很稳定

**Comment by MetsukiMio** [comment]
但是足够把链接变成网页了

**Comment by MetsukiMio** [comment]
你看看，绝大多数的第三方启动器都有大量链接

**Comment by MetsukiMio** [comment]
这c#就没那么方便了，javafx的webkit能直接做浏览器，还支持html5和js，c#不仅要自己写，这些东西都要自己实现，因为mcmod有大量的js

**Comment by CarmJos** [comment]
加油，有更多问题的话建议多用百度、谷歌等搜索软件，我这里关闭issues了哦，再会~

**Comment by CarmJos** [comment]
> if (this.currentUploader.isCommercialize){ System.out.println("这....."); } else{ System.out.println("这才是最正常的up主"); }

另： 强烈建议在日常生活以及文字交流时不要参与代码内容，也许看起来很酷(?)，但在更多人看来这是影响交流效率以至于十分滑稽的事情。

**Comment by MetsukiMio** [comment]
但是如果是与程序员(.contains(you);)交流呢....

**Comment by CarmJos** [comment]
> 但是如果是与程序员(.contains(you);)交流呢....

如果是程序员的话，特别是程序员与程序员之间的话，一般都会觉得这种交流方式特别的愚蠢。

**Comment by MetsukiMio** [comment]
e



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年06月27日 11:51 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [CarmJos/CarmJos] My Launcher Bug Fix (Issue #6) |

但是如果是与程序员(.contains(you);)交流呢....

如果是程序的话，特别是程序愿意程序员之间的话，我觉得这种交流方式特别的愚蠢。
